### ISSUE TITLE
Firebase Web9

### ISSUE THREAD

**Issue by joshuareisbord** [brianjychan/react-spotify-firebase-boilerplate#7]
Hello!

Thank you for the Web 8 boilerplate! It's been helpful to learn how to implement an oAuth2 authorization flow. By any chance do you plan on updating the repository to the new Firebase Web9 SDK?

Thanks!

**Comment by brianjychan** [comment]
Hey Joshua, I'm very glad you found it useful -- however unfortunately with time constraints I've not been able to. It's great somebody's working with the authorization flow + web9 though. I wish you good luck building!

Sent via Superhuman ( ***@***.*** )
